name: Brand Presence Check

on:
  workflow_dispatch: {}
  schedule:
    # каждые 2 дня в 06:00 UTC (≈ 08:00 по Берлину летом)
    - cron: "0 6 */2 * *"

jobs:
  run-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run checker
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_NAME: Brands
          USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
          MAX_PER_RUN: "300"    # на старте устойчивее; потом можно вернуть 600
          SLOW_MS: "900"        # пауза между сайтами (мс): 800–1500
          BATCH_PER_PROXY: "60" # сколько брендов обрабатывать на один прокси/сеанс
          PROXIES: ${{ vars.PROXIES }} # необязательно: comma-separated, напр. http://1.2.3.4:8080,http://user:pass@5.6.7.8:8000
        run: node src/main.mjs
