name: Brand Presence Check

on:
  workflow_dispatch: {}
  schedule:
    # каждые 2 дня в 06:00 UTC
    - cron: "0 6 */2 * *"

jobs:
  run-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Run checker
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_NAME: Brands
          USER_AGENT: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
          MAX_PER_RUN: "600"   # можно уменьшить, напр. 300
          SLOW_MS: "600"       # пауза между сайтами (мс) — увеличьте до 1000–1500, если ловите блокировки
        run: node main.mjs

